title: Copilot Studio Component Quiz
description: Take the Copilot Studio Component Quiz and discover which component you are.
url: https://giorgioughini.github.io
baseurl: /copilot-studio-component-quiz-20260701162737

